language: java
jdk:
  - openjdk7

env:
  global:
    - secure: "RYlud0jfbifFvzt06RKqqsccd0ndqN797maARNDsoWknmUBd0dcZDew4fRE+yT2nHRneCqMrO51J9xvhtr8G9xCCizu/tQ/FOz+CDej/gVqevrjpSBMrH1n5lQPGu+cHwa1fAM4gBsd6yGnjJOT4iY/0SBp8JmGQ7b5WsWsR2CM="
    - secure: "NwfsSxtSdK9J2SQaii5a3hpDnJLL+dCd0LCLyujPYOvXD/aVAx6KdKd/YmTpeRYhrlRASsv6P+VJzDsEXnFc3UY9R9iI74En9uo/oicQ8Ubm+Y2AuPXwd7LfAFewEg9iGU6BljEy5+pxaBbPOC2QWipNrD2Pld5LUWI8Z6FPII4="

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq sshpass
 - echo "graphwalker.org,62.75.191.213 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAtt0gW2tGz1f60qs4mSteVq+AhWAw7xYak3+UegaWSwxVh9MpqG/JDRF5CpzTiUvyXlhlAYZ6kCVT5G4zXNNC7ty9UuA5D2PicGOWsF73KGLu6GbmRQTrTMf5ji/IkrFoJysNaXPIbqkwX0TB3DoTyXfE/HoP2JSGwVi5tztUaOc=" > ~/.ssh/known_hosts

script:
 - sshpass -p $GW_PASSWORD rsync -omit-dir-times -avz ./ $GW_USER@graphwalker.org:/var/www
